version: "3.6"
services:
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped
    ports:
        - 88:80
    volumes:
      - /share/homes/gotlieb/organizr:/config
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Moscow
